/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.mskcc.oncokb.controller.api;

import org.mskcc.oncokb.model.PatientData;
import org.mskcc.oncokb.model.Trial;
import org.mskcc.oncokb.model.TrialMatch;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-10T10:25:19.794-04:00")

@Api(value = "trials", description = "the trials API")
public interface TrialsApi {

    @ApiOperation(value = "", notes = "Load trial data into Mongo DB.", response = Void.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Load to Mongo DB successfully.", response = Void.class),
        @ApiResponse(code = 500, message = "Load the trial failed!", response = Void.class) })

    @RequestMapping(value = "/trials/createTrial",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    public ResponseEntity<Void> createTrial(@ApiParam(value = "a trial json object " ,required=true )  @Valid @RequestBody Trial trial);


    @ApiOperation(value = "", notes = "Load patient data into Mongo DB.", response = Void.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Save patient data to Mongo DB successfully!", response = Void.class),
        @ApiResponse(code = 500, message = "Save patient data to Mongo DB failed!", response = Void.class) })

    @RequestMapping(value = "/trials/loadPatientData",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    public ResponseEntity<Void> loadPatient(@ApiParam(value = "clinical and genomic data of a patient" ,required=true )  @Valid @RequestBody PatientData patient);


    @ApiOperation(value = "", notes = "Match trial in Mongo DB to patient.", response = TrialMatch.class, responseContainer = "List", tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Match trials successfully!", response = TrialMatch.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "Match trials failed!", response = Void.class) })

    @RequestMapping(value = "/trials/match",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.GET)
    public ResponseEntity<Void> matchTrial();

}
