# API-first development with swagger
# This file will be used at compile time to generate Spring-MVC endpoint stubs using swagger-codegen
swagger: '2.0'
info:
  title: Matchminer Curate API
  version: 0.0.1
schemes:
- "http"
paths:
  '/mongo/loadTrial':
    post:
      description: Load trial data into Mongo DB.
      operationId: "loadTrial"
      parameters:
      - name: "TrialJson"
        in: "body"
        description: "a trial json object "
        required: true
        schema:
          type: object
          required:
            - trial
          properties:
            trial:
              type: object
      responses:
        '200':
          description: Load to Mongo DB successfully.
        '400':
          description: The json object is invalid.
        '404':
          description: The json object was not found.
        default:
          description: Unexpected error.
  '/match':
    post:
      description: Match trial in Mongo DB to patient or sample.
      operationId: "match"
      parameters:
      - name: "queryData"
        in: "body"
        description: "clinical data and genomic data json objects"
        required: true
        schema:
          type: object
          required:
            - clinical
            - genomic
          properties:
            clinical:
              type: object
            genomic:
              type: object
      responses:
        '200':
          description: Match trial successfully.
        '400':
          description: The json object is invalid.
        '404':
          description: The json object was not found.
        default:
          description: Unexpected error.
