# API-first development with swagger
# This file will be used at compile time to generate Spring-MVC endpoint stubs using swagger-codegen
swagger: '2.0'
info:
  title: Matchminer Curate API
  version: 0.0.1
schemes:
- "http"
tags:
- name: "trials"
  description: "Trials Resource"
paths:
  '/trials/create':
    post:
      description: Load trial data into Mongo DB.
      operationId: "create"
      consumes:
      - "application/json"
      parameters:
      - name: "Trial"
        in: "body"
        description: "a trial json object "
        required: true
        schema:
            $ref: "#/definitions/Trial"
      responses:
        '200':
          description: Load to Mongo DB successfully.
        '500':
          description: Load the trial failed!
definitions:
  Trial:
    type: "object"
    required:
    - "nctId"
    properties:
      archived:
        type: "string"
      curationStatus:
        type: "string"
      nctId:
        type: "string"
      longTitle:
        type: "string"
      phase:
        type: "string"
      shortTitle:
        type: "string"
      status:
        type: "string"
      treatmentList:
        type: "string"
