/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.mskcc.oncokb.controller;


import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import io.swagger.annotations.ApiParam;

/**
 *
 * @author jingsu
 */
@Controller
public class TestController {

    @RequestMapping(value="/trial/{id}", method = RequestMethod.GET)
    public @ResponseBody String getTrialContent(
        @ApiParam(value = "id", required = true)  @PathVariable("id") String id){
        System.out.println(System.getenv("CATALINA_HOME"));
        return "This is trial controller: " + id + "ENV: " + System.getenv("CATALINA_HOME");
    }

}
